### PR TITLE
Updated end of line character sequence to CRLF rather than LF

### PR DESCRIPTION
**Pull request by juanqui**
According to RFC 959 (https://www.ietf.org/rfc/rfc959.txt), the end-of-line sequence for FTP commands should be CRLF and not LF. Most FTP server implementations don't care and support either, but Microsoft's IIS/FTP solution is picky and will return a 451 error response due to the invalid line termination (see https://support.microsoft.com/en-us/kb/2505047).

### CODE REVIEW

**Comment by juanqui** [comment]
Btw, great project @pohmelie !!

**Comment by pohmelie** [comment]
Awesome!
* Probably we should make constant with name CRLF or EOL in common.py for client and server usage. And what about our mlsd and list workers? Should we send \r\n instead of \n in this case?
* I have no experience with writing setup.py, but can we use version as:
```python
import aioftp
...
args = dict(
    name='aioftp',
    version=aioftp.__version__,
```
* And what about publishing? Cause flit don't collect setup.py to wheel (I think).

Thanks for pull! :+1:

**Comment by rsichny** [comment]
"The argument field consists of a variable length character string
      ending with the character sequence <CRLF> (Carriage Return, Line
      Feed) for NVT-ASCII representation; for other negotiated languages
      a different end of line character might be used"

regarding setup.py - imo it would be better to use configparser and parse flit.ini into setup() args - then we'll have descriptions in one place (flit.ini) though setup.py will be supported too.

**Comment by rsichny** [comment]
I'd wote for client to check "SYST" and in case of "unix" in response use LF, otherwise CRLF.

**Comment by pohmelie** [comment]
@rsichny is there a possibility to server to deal with "\n" and not with "\r\n"? From same rfc:

    End-of-Line
         The end-of-line sequence defines the separation of printing
         lines.  The sequence is Carriage Return, followed by Line Feed.

And if we create duality of LF/CRLF on client, what we should do on server? Server can't determine client system.

**Comment by rsichny** [comment]
@pohmelie guess the server should always use CRLF in command connection, as stated by RFC

**Comment by pohmelie** [comment]
@rsichny yeah, that is what I talking about. So server send CRLF always, but client send CR or CRLF? This looks strange. I mean, if client and server are so «smart», why not use CRLF everywhere?

**Comment by juanqui** [comment]
Technically clients should only send CRLF according to the spec. Some clients only send LF and that's probably a bug or has some legacy reason for being. Servers tend to handle both for maximum compatibility (unless you are Microsoft...)

**Comment by juanqui** [comment]
@pohmelie Didn't mean to add all those commits to this pull request! Just the line ending contribution.

**Comment by pohmelie** [comment]
I will refactor this a bit. Move EOL to common.py and use it both server and client.

**Pull request merged**
