### PR TITLE
constants should have uppercase names

### PR DESCRIPTION
**Pull request by rsichny**

### CODE REVIEW

**Comment by pohmelie** [comment]
I think `END_OF_LINE` is more informative than `CRLF`.

**Comment by rsichny** [comment]
ftplib, smtplib, email.utils - everywhere it's called CRLF ;)

**Comment by pohmelie** [comment]
I know, but this looks wrong for me. What is CRLF? It's just two special characters, why somebody should prefer «strange» abbreviation instead of human name? CRLF about bytes, not about end of line.

**Comment by rsichny** [comment]
changed

**Comment by pohmelie** [comment]
Awesome!

**Pull request merged**
